student_name = input("Enter Student Name: ")
father_name = input("Enter Father's Name: ")
mother_name = input("Enter Mother's Name: ")
roll_no = input("Enter Roll No: ")
course = input("Enter Course: ")
fees = input("Enter Fees: ")
college_name = input("Enter College Name: ")
place = input("Enter Place: ")
mobile_no = input("Enter Mobile No: ")
adhar_no = input("Enter Aadhar Card No: ")
pan_no = input("Enter PAN Card No: ")
print("\n===== Student Information =====")
print("Student Name :",student_name)
print("Father's Name :",father_name)
print("Mother's Name :",mother_name)
print("Roll Number :",roll_no)
print("Course :",course)
print("Fees :",fees)
print("College Name :",college_name)
print("Place :",place)
print("Mobile Number :",mobile_no)
print("Aadhar Card Number :",adhar_no)
print("PAN Card Number :",pan_no)